### ISSUE TITLE
How to stack furniture in travisojs?

### ISSUE THREAD

**Issue by mtwzim** [axaq/traviso.js#15]
Hello guys, I'am starting to create a project with travisojs and I would like to know how I can place items over other items in my game, below I leave a demonstration of stacking items which is what I want to do.

http://puu.sh/cGXsI/9450bae0ca.gif

i not see about in documentation.

**Comment by axaq** [comment]
Hi @mtwzim 
Unfortunately vertical layers is not implemented yet in Traviso. You can probably do it by fiddling with the code and I can suggest considering having different layers of map stacked on top as an easy starting point. But it doesn't come as an out of the box feature at the moment.

**Comment by mtwzim** [comment]
Ok, thank u for response.
