### ISSUE TITLE
How do I get the tile position from the cursor position?

### ISSUE THREAD

**Issue by fax1ty** [axaq/traviso.js#16]
Also it would be very convenient if there was an event that was responsible for pointing the mouse at the object/tile, and not just when clicking

**Comment by axaq** [comment]
it is costly in terms of performance. but you can look at this method if you want to implement it anyway: https://github.com/axaq/traviso.js/blob/881652092fc417fd8671e215a302655700494513/bin/traviso.dev.js#L3972
