### ISSUE TITLE
Haritaları nasıl oluşturucaz

### ISSUE THREAD

**Issue by AhmetOZALP** [axaq/traviso.js#3]
Merhaba Hakan bu scriptte haritaları bi progrma yardımı ilemi açıyoruz bunun bilgisini goremedim de

**Comment by AhmetOZALP** [comment]
Haritanın json ve png kısımlarını TexturePackerGUI den yapıyoruz kullanmasıın vs biliyorum bunu ama "mapData.xml" dosyasını biz manuel mi oluşturcaz?

**Comment by axaq** [comment]
Selam Ahmet. Evet mapData.xml tamamen manuel. Ek program ihtiyaci yok. Ornek xml'lerde aciklayici commentler bulabilirsin. Ayrica asagidaki linkte bir tutorial mevcut.

[Data File Structure](http://www.travisojs.com/blog/tutorial/2015/03/15/data-file-structure.html)

Sadece spritesheet'ler icin TexturePacker kullanabilirsin dedigin gibi ama bu da zorunlu degil. Istersen gorselleri tek tek de yukleyebilirsin. Gorselleri istersen traviso'yu baslatmadan once kendin yukleyebilir ya da  'assetsToLoad' parametresini kullanarak traviso'ya yukletebilirsin. 

(gec cevap icin kusura bakma, tatildeydim)

**Comment by AhmetOZALP** [comment]
açıkcası sana birazcık sorularım var phaser vs baktım baya ama phaser isometric kutupanesinde hatalar var ve kodları yazan kişi destek vermiyor senin isometrici çok sevdim güzel yazmışın sadece 1-2 soru daha sorcam sana


Ben bu ssitemi online chat gibi bi oyun için yazcam;
- Birden fazla eleman nasıl yaparım (nodejs den konumları hareket edilebilir şekılde)
- Hareket eden verilerin ustunde chat gibi bişi oluşturmak istiyorum son olarak bunu anlarsam daha hakim olabilirim az ingilizcem var kutupanende ingilizce tam anlamayanmadım yazmışın ama :)

**Comment by AhmetOZALP** [comment]
Bknz: https://img-oyunstudyosu.mncdn.com/global/web/assets/img/content/portfolio/yosun-palas.png?v=1.9

**Comment by axaq** [comment]
Selam Ahmet,

Oncelikle onerim, eger ingilizce'de sorun yasiyorsan, kutuphane ile gelen orneklerden birini alip onun ustunden degistirerek ilerlemen olur. Sorularina gelince:

- Birden fazla eleman nasıl yaparım

Traviso'da `controllable`, mouse yardimiyla hareket edebildigin objeler demek. Onun disinda butun objeler zaten serbest. Yani herhangi bir objeyi `checkAndMoveObjectToTile` ya da `addObjectToLocation` gibi fonksiyonlari kullanarak istedigin yere yerlestirebilirsin. 

[Documentation](http://www.travisojs.com/docs/classes/EngineView.html)

-  Hareket eden verilerin ustunde chat gibi bişi oluşturmak istiyorum

Bu biraz da pixi.js'e ne kadar hakim olduguna bagli. pixi bircok acidan actionscript'e benzer sekilde yazildi. Yani sprite'larin ve layer'larin var. Ornegin traviso'daki harita (yer) tek basina bir layer. Ustundeki objeler (ya da karakterler) ise ayri bir layer. Dolayisiyla sen de chat icin ayri bir layer (DisplayObject) yaratip chat balonlarini burda gosterebilirsin. Tabi bu bir yol sadece. Nasil yapacagina sen karar vereceksin. Ornegin asagidaki oyun traviso ile yapildi ve karakterlerin ustunde baska objeler gosterebiliyor.

[Evermoor game](http://games.disney.co.uk/the-evermoor-chronicles/evermoor-high)

**Comment by AhmetOZALP** [comment]
Layerleri vs farkettim tiles ler var en altta onun ustunde layerler sabit ve hareket eden layerler olarak ayırmışın xml de yazdıgın kutupaneyi iyicene gozden geçirmem lazım katkıdad bulunurum sadece az mantıgını anlayabilirsem kutupanenin yeterli pixijs hiç bilmedigim için zorluk çekiyorum şuan sanırım

**Comment by AhmetOZALP** [comment]
Tekrar merhaba oyuncu hareket tuşunu fareden sağ tuşa nasıl alırız?

**Comment by axaq** [comment]
Selam Ahmet. Bunun icin travisonun mouse listener metodlarini iptal edip kendi keyboard listener methodlarini eklemelisin. Cok zor olacagini sanmam. 

Bu arada bu entry'yi kapaticam cunku github issue'lari daha cok hata raporlama ya da ozellik degerlendirme icin kullanilir. Istersen daha sonraki sorularini Traviso'nun kendi blogundaki comment bolumunden sor. Herhangi bir postun altina yazman yeterli, oraya da buraya baktigim gibi bakiyorum.

[Traviso blog](http://www.travisojs.com/blog/)

Umarim Traviso isine yariyordur ve yakin zamanda bir oyun/uygulama gorebiliriz.

**Comment by AhmetOZALP** [comment]
Blog yorumlarına bakmıyorsun sanırım?
