### ISSUE TITLE
common js support

### ISSUE THREAD

**Issue by jnmandal** [axaq/traviso.js#7]
Hey @axaq, thanks for making this. It seems great. Is there any plan to add support for commonjs? Maybe we could even publish it on npm? 

I'd be happy to help out w/ it.

**Comment by axaq** [comment]
Hey @jnmandal, 

Sorry for the late response. commonjs support along with the basic js version would be a great addition. 

To be honest, I have a lot of things in mind to improve traviso including latest standards and advanced features but my work consumes a lot of my time at the moment. 

It sounds like you have experience with commonjs and convertions. May be we can use this thread/issue to create a little roadmap for it. I would appreciate any help and please let me know what kind of help you can offer.

**Comment by axaq** [comment]
With the latest release traviso is now on npm supporting both commonjs and es modules.
